### ISSUE TITLE
Publishing integrations with space:script:inject scope is not allowed

### ISSUE THREAD

**Issue by JackBailey** [GitbookIO/integrations#185]
I'm trying to create a Umami integration, forked from the Plausible one but I'm getting the error `Publishing integrations with space:script:inject scope is not allowed`.

I'm just trying to publish it privately for now, how do I resolve this?

My gitbook-manifest.yml:

```yml
name: Umami
title: Umami
organization: cBtGw0QchuEMpqSwIWJB
icon: ./assets/icon.png
description: Receive GitBook traffic insights directly in your Umami dashboard.
previewImages:
    - ./assets/plausible-preview.png
externalLinks:
    - label: Documentation
      url: https://www.gitbook.com/integrations/plausible
visibility: public
script: ./src/index.ts
scopes:
    - space:script:inject
contentSecurityPolicy:
    script-src: |
        https://plausible.io;
    connect-src: |
        plausible.io
        *;
summary: |
    # Overview

    Plausible Analytics are a GDPR CCPA and cookie law compliant site analytics. Web analytics is the process of measuring and analyzing the usage of a website. With Plausible activated on your website, you get access to a simple open source analytics dashboard. You can then use this data to assess the performance of your site and to figure out what you can do to improve your future efforts.

    # How it works

    The GitBook Plausible Analytics integration allows you to track traffic in your published spaces from your Plausible dashboard. Automatic tracking in your documentation: Each of your connected GitBook spaces will fetch the cookie-less Plausible tracking script and inject it in your public content.

    # Configure

    You can enable the integration on single published space by navigating to the sub-navigation and clicking on Integrations button. If you prefer to enable  the integration or multiple or all published spaces you can do so by navigating to the org settings and clicking the Integrations tab. You will need your Domain to finish the configuration.
categories:
    - analytics
configurations:
    space:
        properties:
            website:
                type: string
                title: Website ID
                description: The Website ID you configured for this Umami website.
            api:
                type: string
                title: Self-hosted API
                description: When self-hosting, configure the url of the instance API (empty when using analytics.umami.is).
        required:
            - website

```
